/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
}
